---
all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local

    lb:
      hosts:

    elk:
      hosts:
        10.12.1.34:
        10.12.1.35:
        10.12.1.36:

    monitoring:
      hosts:
        10.12.1.37:
        
  vars:
    ansible_user: uclv
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
