---
# roles/common/tasks/main.yml
- name: Instalar utilidades y dependencias base para el stack ELK
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
      - curl
      - jq
      - htop
    state: present

- name: Aumentar vm.max_map_count en sysctl (Requisito crítico para Elasticsearch)
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    sysctl_set: yes
    reload: yes
  when: inventory_hostname in groups['elk']

- name: Configurar zona horaria (Establecer America/Havana)
  community.general.timezone:
    name: America/Havana

- name: Agregar clave GPG de Elastic
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /usr/share/keyrings/elasticsearch-keyring.gpg
    mode: '0644'
  environment:
    http_proxy: "http://{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "http://{{ proxy_host }}:{{ proxy_port }}"

- name: Agregar repositorio de Elastic
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main"
    state: present
    filename: elastic-9.x
  environment:
    http_proxy: "http://{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "http://{{ proxy_host }}:{{ proxy_port }}"